
FROM tomcat:8.0
ADD 'http://localhost:8099/job/petclinic/lastBuild/org.springframework.samples$petclinic_sdk/artifact/org.springframework.samples/petclinic_sdk/1.0.0-SNAPSHOT/petclinic_sdk-1.0.0-SNAPSHOT.war' /usr/local/tomcat/webapps/
